Repository Arun9739/Paryatana, pull requests merged in 2022-10, with the labels that each got.

#17 links added to the contacts icon
  contact.html
Labels: enhancement, hacktoberfest, Changes-pending

#36 Added Shimla and Kashmir Img
  img/index-01.jpg
  img/index-02.jpg
Labels: hacktoberfest, Changes-pending

#42 Made Navbar fixed at the top on scroll
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 Added Scroll to Top Button
  about.html
  contact.html
  css/scrollToTop.css
  index.html
  js/scrollToTop.js
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 Send email by clicking SUBMIT button
  contact.html
  js/email.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#48 Made changes to navbar
  css/templatemo-style.css
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#52 Corrected spelling of the website name in the contact page
  contact.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#55 Added functionality to the Learn More button
  about.html
  index.html
  tours.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#68 Removed home tab from the navbar and made the logo clickable to go to…
  about.html
  contact.html
  css/Homenavbar.css
  css/templatemo-style.css
  index.html
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#54 Slideshow effect to image slider of About page
  about.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#72 Replaced Images with relevant Images
  img/index-07.jpg
  img/index-08.jpg
  img/index-09.jpg
  img/index-10.jpg
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#76 Aligned Boxes under our Tour section in Our Tour page
  css/templatemo-style.css
  tours.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#71 Add Indian rupees symbol instead of dollor symbol [fixes #69]
  index.html
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Added styling to about us page cards and icons
  about.html
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#79 Added Preloader and Favicons, fixed some minor bugs
  css/scrollToTop.css
  css/templatemo-style.css
  favicon/about.txt
  favicon/android-chrome-192x192.png
  favicon/android-chrome-512x512.png
  favicon/apple-touch-icon.png
  favicon/favicon-16x16.png
  favicon/favicon-32x32.png
  favicon/favicon.ico
  favicon/site.webmanifest
  img/preloader.gif
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#85 Updated contact.html and added js/gmap.js
  contact.html
  js/gmap.js
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#110 fixed use of hardcoded values for links on the homepage
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#103 Changes done
  about.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#114 added favourite section
  favourites.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#123 Added Commen Section for Interactivity
  about.html
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#130 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#116 Added Trendy Card Design
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#131 added smooth animation and responsiveness
  about.html
Labels: enhancement, hacktoberfest, Changes-pending

#136 Added developer profile link in copyright section
  about.html
  contact.html
  css/templatemo-style.css
  favourites.html
  index.html
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#155 updated catchphrases for popular packages
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#158 Fix favicon
  about.html
  contact.html
  favourites.html
  tours.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#160 Master
  about.html
  contact.html
  css/templatemo-style.css
  index.html
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#132 fixed the card responsiveness for tablet view in home page
  css/templatemo-style.css
  index.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#166 Hover Effect On Tour Packages In Home & Tour Page
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#167 Added box shadow to places cards
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#171 Removed un-necessay extra social links
  contact.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#153 added more favourite places in favourite.html
  favourites.html
  img/index-11.jpg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#179 Added hover and active effects to input fields and Fixed card alignment issue
  css/bootstrap.min.css
  css/font-awesome.min.css
  css/templatemo-style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#181 Buttons and links styling improved
  about.html
  contact.html
  css/templatemo-style.css
  index.html
  tours.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#198 Shadow effect of Our Tours corrected
  tours.html
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#202 UI of Contact Us form improved
  contact.html
  css/bootstrap.min.css
  css/templatemo-style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#219 Update footer.css
  css/footer.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#216 BUG FIX: "Travel" button get more visible while hover
  css/templatemo-style.css
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#203 feat: Add mobile-menu-icon animation (re-submission)
  about.html
  contact.html
  css/templatemo-style.css
  favourites.html
  index.html
  js/templatemo-script.js
  tours.html
Labels: enhancement, hacktoberfest, Changes-pending

#230 Update footer.css
  css/footer.css
Labels: enhancement, hacktoberfest, Changes-pending

#231 fixed the margin issue and background coloring
  css/bootstrap.min.css
  favourites.html
  index.html
  tours.html
Labels: hacktoberfest, bug-fixing, Changes-pending

#220 Responsive Logo in Navbar and Footer.
  css/footer.css
  css/logo.css
Labels: enhancement, hacktoberfest, Changes-pending

#228 Fixed fav icon error in title bar
  about.html
  contact.html
  index.html
  tours.html
Labels: hacktoberfest, bug-fixing, Changes-pending

#240 Update templatemo-style.css
  css/templatemo-style.css
Labels: hacktoberfest, bug-fixing, Changes-pending

#238 Updated Footer Followup Design
  css/footer.css
Labels: hacktoberfest, bug-fixing, hacktoberfest-accepted

#269 Added links for all social media
  about.html
Labels: enhancement, hacktoberfest, Changes-pending

#276 'Our Tours' page changes (#272)
  css/templatemo-style.css
  tours.html
Labels: hacktoberfest

#283 Issue #245
  css/templatemo-style.css
  index.html
  tours.html
Labels: hacktoberfest, bug-fixing, Changes-pending

#309 fixed footer and cards
  css/footer.css
  css/templatemo-style.css
  favourites.html
  img/FCDD44.png
  index.html
Labels: enhancement, hacktoberfest, Changes-pending

#314 Link functionalities
  about.html
  tours.html
Labels: hacktoberfest, bug-fixing, Changes-pending

#321 Fix: Bgrd & color of "YOUR GO TO TRAVEL PARTNER"
  css/parallax-only.css
  index.html
Labels: enhancement, hacktoberfest, Changes-pending

#334 Add accurate images
  img/tours-03.jpg
  img/tours-04.jpg
  img/tours-05.jpg
  img/tours-06.jpg
Labels: hacktoberfest, bug-fixing, Changes-pending

#343 fix issue #340 Logo placement is wrong
  about.html
  contact.html
  css/logo.css
  favourites.html
  index.html
  tours.html
Labels: hacktoberfest, bug-fixing, Changes-pending

#351 Update hero.css and README.md
  README.md
  css/hero.css
Labels: enhancement, hacktoberfest, Changes-pending
